<?php

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;

function godpanel_profile_install() {
  // Enable default permissions for system roles.
  user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, ['access comments']);
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, ['access comments', 'post comments', 'skip comment approval']);

  $user = User::load(1);
  $user->roles[] = 'administrator';
  $user->save();
}
